### ISSUE TITLE
File separators on Windows

### ISSUE THREAD

**Issue by lread** [camsaul/whitespace-linter#6]
I'm trying your very cool linter out for rewrite-clj.

When specifying my paths and exclusions, I used the the forward slash as the file separator character.
Often on the JVM, the forward slash is automatically handled on Windows.

Could/should whitespace-linter automatically convert the forward slash file separator when on Windows?
I frankly don't know. Might be trickier for regexes.

FWIW, [I ended up wrapping whitespace-linter in my `build.clj` and doing the necessary conversions there](https://github.com/clj-commons/rewrite-clj/blob/ced60309613a2672b4adc0532948d496a0778d77/build.clj#L91).

**Comment by camsaul** [comment]
Hmm... I think handling forward slashes in the linter would make sense. That way you could use it on the same project on either Windows or *nix. Would you mind submitting a PR?

**Comment by lread** [comment]
Yeah, I could take a crack at it sometime @camsaul.

I'm thinking that on Windows, forward slashes should be equivalent to backslashes for input, but path output should probably still use the native backslash. Does that make sense?

**Comment by camsaul** [comment]
@iread that makes sense to me
