### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by vemv** [camsaul/whitespace-linter#9]
I'd like to integrate this linter into https://github.com/nedap/formatting-stack which makes some things very easy if not already available, e.g.

* only lint certain files, relative to the Git status
* only apply certain rules to certain files

A precondition for this integration would be to offer the lib through Maven, would you be so kind?

Cheers - V

**Comment by camsaul** [comment]
Alright, I can set this up

**Comment by camsaul** [comment]
Ok @vemv, done. https://clojars.org/com.camsaul/whitespace-linter

**Comment by vemv** [comment]
Alright, thanks! Let's see if I can make something cool w/ it.
